service: everdiary

image: takaokouji/everdiary

servers:
  web:
    hosts:
      - 13.112.62.67
    cmd: ./bin/rails server
    env:
      clear:
        DB_HOST: everdiary-db
      secret:
        - LINE_KEY
        - LINE_SECRET
        - LINE_CHANNEL_SECRET
        - LINE_CHANNEL_TOKEN
        - MYSQL_ROOT_PASSWORD
        - RAILS_MASTER_KEY

proxy:
  ssl: true
  host: everdiary.smalruby.app
  app_port: 3000

registry:
  username: takaokouji
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: arm64

# env:
#   clear:
#     - DB_HOST: everdiary-db
#   secret:
#     - RAILS_MASTER_KEY

# aliases:
#   shell: app exec --interactive --reuse "bash"

ssh:
  user: ubuntu
  keys: [ "~/.ssh/everdiary.pem" ]

volumes:
  - "app_storage:/app/storage"

# asset_path: /app/public/assets

# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

accessories:
  db:
    image: mysql:8.0
    roles:
      - web
    port: 3306
    env:
      clear:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        MYSQL_ROOT_HOST: '%'
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      - config/mysql/production.cnf:/etc/mysql/my.cnf
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - mysql-data:/var/lib/mysql

